version: '3'
services:
  db:
    build: containers/postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0.3035
    ports:
      - "3035:3035"
    volumes:
      - .:/advice2
  app:
    build: .
    command: /bin/bash -c "rm -rf tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: webpacker:3035
    volumes:
      - .:/advice2
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    tty: true
    stdin_open: true